version: '3.8'

services:
  image-threat-scanner:
    build: .
    container_name: image-threat-scanner
    ports:
      - "5000:5000"
    volumes:
      # Mount scan directories (adjust paths as needed)
      - ./scan-data:/app/scan-data:ro  # Read-only scan directory
      - ./logs:/app/logs               # Log output
      - ./uploads:/app/uploads         # Temporary uploads
      - ./temp_sessions:/app/temp_sessions  # Session data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - MAX_CONTENT_LENGTH=104857600  # 100MB
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - scanner-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: scanner-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates
    depends_on:
      - image-threat-scanner
    restart: unless-stopped
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge

volumes:
  scan-data:
    driver: local
  logs:
    driver: local